#+TITLE: ∂λ
#+OPTIONS: toc:nil num: nil

This is a personal Guix channel (pronounced "Divya Lambda") by me which aims to mostly fulfil the package requirements of the same, in those casese whence upstream packages are found to be unsatisfactory.

The packages here eventually plan to find themselves in the Guix repository upstream. My specific interests are in packaging Haskell, Rust packages and toolchain, libre audio software, among others.

* Channel Definition
You can add this channel to your configuration by adding the following to =~/.config/guix/channels.scm=:

#+begin_src scheme
  (channel
   (name 'divya-lambda)
   (url "https://codeberg.org/divyaranjan/divya-lambda.git")
   (branch "master")
   (introduction
    (make-channel-introduction
     "fe2010125fcbe003de42436b1a73ab53cc5e828"
     (openpgp-fingerprint
      "F0B3 1A69 8006 8FB8 096A  2F12 B245 10C6 108C 8D4A"))))
#+end_src

* Packages
Here are the packages that are publicly available from the channel:
** Audio
=(divya-lambda audio):=
- =jack-mixer= ([[https://git.savannah.gnu.org/cgit/guix.git/commit/?id=07cd046c209f192032b425d2ee44f6025bff63a1][Merged]] upstream) \\
  https://github.com/jack-mixer/jack_mixer
** Video
=(divya-lambda video):=
- =blue-recorder= ([[https://issues.guix.gnu.org/74432][Sent]] upstream) \\
  https://github.com/xlmnxp/blue-recorder
** Emacs
*** Emacs Builds
=(divya-lambda emacs):=
- =emacs-master=
- =emacs-lucid= ([[https://lists.gnu.org/archive/html/guix-patches/2024-12/msg02003.html][Sent]] upstream)
- =emacs-master-pgtk=
- =emacs-master-lucid=
- =emacs-master-xwidgets=
- =emacs-master-igc=
*** Emacs Packages
=(divya-lambda emacs-xyz):=
- =emacs-binder= ([[https://lists.gnu.org/archive/html/guix-patches/2025-01/msg00016.html][Sent]] upstream)
  https://codeberg.org/divyaranjan/binder

** Rust
*** Apps
=(divya-lambda rust-apps)=:
- =bottom= (Merged upstream)
  https://github.com/ClementTsang/bottom

** Fonts
=(divya-lambda fonts):=
- =font-spline-sans= ([[https://lists.gnu.org/archive/html/guix-patches/2025-01/msg00025.html][Sent]] upstream)
- =font-spline-sans-mono= ([[https://lists.gnu.org/archive/html/guix-patches/2025-01/msg00101.html][Sent]] upstream)
* Patches
The patches for all/most of the packages in this channel that were sent to upstream Guix can also be found in the =patches/= directory.
* Other Channels
These are some other interesting channels worth checking out:

- [[https://codeberg.org/anemofilia/radix][GNU/Radix]]
- [[https://github.com/umanwizard/guix-rust-next][rust-next]]
